POST http://localhost:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "vmarttil",
    "email": "ville.marttila@iki.fi",
    "password": "test"
}

###

POST http://localhost:8080/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "vmarttil",
    "password": "test"
}

####

GET http://www.localhost:8080/api/test/player HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTkwNjEwMjk3LCJleHAiOjE1OTA2OTY2OTd9.Fs8-4JbMWVl692uSYZBEU0vMyKjwh8vRLMR-l6PmsVM
